INSERT INTO ROLE (LIBELLE) VALUES ('Étudiant')
INSERT INTO ROLE (LIBELLE) VALUES ('Directeur Établissement')
INSERT INTO ROLE (LIBELLE) VALUES ('Directeur Études')

INSERT INTO FILIERE (ABREVIATION, NOM_FILIERE)VALUES('IR','Informatique et Réseaux')
INSERT INTO FILIERE (ABREVIATION, NOM_FILIERE)VALUES('SEP','Sécurité, Environnement et Prévention')

INSERT INTO STATUS (LIBELLE)VALUES('En cours')
INSERT INTO STATUS (LIBELLE)VALUES('Résolu')

INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('Daniels','Jack','jdaniel','whisky',2,1)
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('RICHARD','Antoine','arichard','arichard',1,1)
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('SABARON','Benjamin','bsabaron','bsabaron',1,1)
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('MARTY','Benjamin','bmarty','bmarty',2,1)
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('Morgan','Captain','cmorgan','rhum',null,3)
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_FILIERE,ID_ROLE) VALUES ('Meister','Jager','jmeister','liqueur',null,2)

--INSERT INTO PROBLEME (CONTENU, DATE_HEURE, OBJET, VOTE, ID_PERSONNE, ID_STATUS)VALUES('contenu du probleme 1', '1509380153','probleme 1',4,1,1)
--INSERT INTO PROBLEME (CONTENU, DATE_HEURE, OBJET, VOTE, ID_PERSONNE, ID_STATUS)VALUES('contenu du probleme 2', '1509380153','probleme 2',0,5,1)
--INSERT INTO PROBLEME (CONTENU, DATE_HEURE, OBJET, VOTE, ID_PERSONNE, ID_STATUS) VALUES ('contenu du probleme 3', '1509380153', 'probleme 3',3,2,2)


