create table personne (
	id_personne integer generated by default as identity,
	login varchar(255), 
	nom varchar(255), 
	password varchar(255), 
	prenom varchar(255), 
	id_role integer, 
	primary key (id_personne)
);
	
create table role (
	id_role integer generated by default as identity, 
	nom_role varchar(255), 
	primary key (id_role)
);

create table status (
	id_status integer generated by default as identity, 
	nom_status varchar(255), 
	primary key (id_status)
);

create table filiere (
	id_filiere integer generated by default as identity, 
	nom_filiere varchar(255), 
	abreviation varchar(255), 
	primary key (id_filiere)
);

create table probleme (
	id_probleme integer generated by default as identity, 
	objet varchar(255), 
	contenu varchar(255), 
	vote integer,
	id_status integer,
	primary key (id_probleme)
);

INSERT INTO ROLE (LIBELLE) VALUES ('Étudiant');
INSERT INTO ROLE (LIBELLE) VALUES ('Directeur Établissement');
INSERT INTO ROLE (LIBELLE) VALUES ('Directeur Études');

INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_ROLE) VALUES ('Daniels','Jack','jdaniel','whisky',1);
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_ROLE) VALUES ('Morgan','Captain','cmorgan','rhum',3);
INSERT INTO PERSONNE (NOM,PRENOM,LOGIN,PASSWORD,ID_ROLE) VALUES ('Meister','Jager','jmeister','liqueur',2);

alter table personne add constraint UK_id_role unique (id_role);
alter table personne add constraint FK_id_role foreign key (id_role) references role;