Hibernate: create table filiere (id_filiere integer generated by default as identity, abreviation varchar(255), nom_filiere varchar(255), primary key (id_filiere))
Hibernate: create table personne (id_personne integer generated by default as identity, login varchar(255), nom varchar(255), password varchar(255), prenom varchar(255), id_role integer, primary key (id_personne))
Hibernate: create table probleme (id_probleme integer generated by default as identity, contenu varchar(255), objet varchar(255), vote integer, id_status integer, primary key (id_probleme))
Hibernate: create table role (id_role integer generated by default as identity, libelle varchar(255), primary key (id_role))
Hibernate: create table status (id_status integer generated by default as identity, libelle varchar(255), primary key (id_status))
Hibernate: alter table personne add constraint UK_d4qp7k1u0w4e8ity04o22yovq unique (id_role)
Hibernate: alter table probleme add constraint UK_sryb1cwnvmltroumt080h68f0 unique (id_status)
Hibernate: alter table personne add constraint FKlo0t6okha7liaa1yum0bcndyp foreign key (id_role) references role
Hibernate: alter table probleme add constraint FKw37be2jstqt6yueh8v5go964 foreign key (id_status) references status